resources:
- url: '/local/lovelace/column-card.js?1555563408.2231936'
  type: js
- url: '/local/lovelace/mini-media-player.js?1555563408.2231936'
  type: module
- url: '/local/lovelace/monster-card.js?1555563408.2231936'
  type: js
- url: '/local/lovelace/vertical-stack-in-card.js?1555563408.2231936'
  type: js

title: Home

views:
  - !include lovelace/00_overview.yaml
  - !include lovelace/10_lights.yaml
  - !include lovelace/20_security.yaml
  - !include lovelace/30_media.yaml
  - !include lovelace/40_cameras.yaml
  - !include lovelace/50_network.yaml
