# Sensors
sun:
sensor:
  - platform: season
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - cloud_cover
      - humidity
      - precip_probability
      - temperature
      - nearest_storm_distance
